function [featureTable,ranking,outputTable] = featureRanking(inputData,EVENT)
%DIAGNOSTICFEATURES recreates results in Diagnostic Feature Designer.
%
% Input:
%  inputData: A table or a cell array of tables/matrices containing the
%  data as those imported into the app.
%
% Output:
%  featureTable: A table containing all features and condition variables.
%  ranking: A table containing ranking scores for selected features.
%  outputTable: A table containing the computation results.
%
% This function ranks computed feautres using algorithms:
%  One-way ANOVA
%
% Organization of the function:
% 1. Compute signals/spectra/features
% 2. Extract computed features into a table
% 3. Rank features
%
% Modify the function to add or remove data processing, feature generation
% or ranking operations.

% Auto-generated by MATLAB on 08-Jan-2026 13:26:16

FEATURES = ["mean_Altitude"; "std_Altitude"; "rms_Altitude"; "kurtosis_Altitude"; "skewness_Altitude";
    "mean_Mach"; "std_Mach"; "rms_Mach"; "kurtosis_Mach"; "skewness_Mach";
    "mean_Pamb"; "std_Pamb"; "rms_Pamb"; "kurtosis_Pamb"; "skewness_Pamb";
    "mean_TAT"; "std_TAT"; "rms_TAT"; "kurtosis_TAT"; "skewness_TAT";
    "mean_Pt2"; "std_Pt2"; "rms_Pt2"; "kurtosis_Pt2"; "skewness_Pt2";
    "mean_WFuel"; "std_WFuel"; "rms_WFuel"; "kurtosis_WFuel"; "skewness_WFuel";
    "mean_VAFN"; "std_VAFN"; "rms_VAFN"; "kurtosis_VAFN"; "skewness_VAFN";
    "mean_VBV"; "std_VBV"; "rms_VBV"; "kurtosis_VBV"; "skewness_VBV";
    "mean_Fan_Speed"; "std_Fan_Speed"; "rms_Fan_Speed"; "kurtosis_Fan_Speed"; "skewness_Fan_Speed";
    "mean_Core_Speed"; "std_Core_Speed"; "rms_Core_Speed"; "kurtosis_Core_Speed"; "skewness_Core_Speed";
    "mean_T25"; "std_T25"; "rms_T25"; "kurtosis_T25"; "skewness_T25";
    "mean_T3"; "std_T3"; "rms_T3"; "kurtosis_T3"; "skewness_T3";
    "mean_Ps3"; "std_Ps3"; "rms_Ps3"; "kurtosis_Ps3"; "skewness_Ps3";
    "mean_T45"; "std_T45"; "rms_T45"; "kurtosis_T45"; "skewness_T45";
    "mean_P25"; "std_P25"; "rms_P25"; "kurtosis_P25"; "skewness_P25";
    "mean_T5"; "std_T5"; "rms_T5"; "kurtosis_T5"; "skewness_T5"];
INDEPENDENT_VARIABLES = EVENT + "_index";
CONDITION_VARIABLES = "fault_" + EVENT;

% Create output ensemble.
outputEnsemble = workspaceEnsemble(inputData,'DataVariables',FEATURES, ...
    'IndependentVariables',INDEPENDENT_VARIABLES, ...
    'ConditionVariables',CONDITION_VARIABLES);


% Gather all features into a table.
selectedFeatureNames = FEATURES;
featureTable = readFeatureTable(outputEnsemble,'Features',selectedFeatureNames);

% Feature ranking for FeatureTable1

% Get selected features and labels for classification ranking.
selectedFeatureValues = featureTable{:,selectedFeatureNames};
label = featureTable{:,CONDITION_VARIABLES};

% Convert label to numeric values.
if iscategorical(label)
    label = string(label);
end
group = grp2idx(label);

% Initialize an empty matrix to store ranking scores.
score = zeros(numel(selectedFeatureNames),0);

% Initialize a string array to store ranking method names.
methodList = strings(0);

%% One-way ANOVA
% Normalize features using minmax.
fNorm = (selectedFeatureValues-min(selectedFeatureValues,[],1))./(max(selectedFeatureValues,[],1)-min(selectedFeatureValues,[],1));

% Compute ranking score using One-Way ANOVA.
numFeatures = size(fNorm,2);
z = zeros(numFeatures,1);
for k = 1:numFeatures
    [~,tbl] = anova1(fNorm(:,k),group,'off');
    % Get the F-statistic from the output of one-way ANOVA.
    stats = tbl{2,5};
    if ~isempty(stats)
        z(k) = stats;
    end
end

% Append new score and method name.
score = [score,z];
methodList = [methodList,"One-way ANOVA"];


%% Create ranking result table.
featureColumn = table(selectedFeatureNames(:),'VariableNames',{'Features'});
ranking = [featureColumn array2table(score,'VariableNames',methodList)];
ranking = sortrows(ranking,'One-way ANOVA','descend');

% Set SelectedVariables to select variables to read from the ensemble.
outputEnsemble.SelectedVariables = unique([outputEnsemble.DataVariables;outputEnsemble.ConditionVariables;outputEnsemble.IndependentVariables],'stable');

% Gather results into a table.
outputTable = readall(outputEnsemble);
end
