function [featureTable,ranking,outputTable] = featureRanking(inputData,EVENT)
%DIAGNOSTICFEATURES recreates results in Diagnostic Feature Designer.
%
% Input:
%  inputData: A table or a cell array of tables/matrices containing the
%  data as those imported into the app.
%
% Output:
%  featureTable: A table containing all features and condition variables.
%  ranking: A table containing ranking scores for selected features.
%  outputTable: A table containing the computation results.
%
% This function ranks computed feautres using algorithms:
%  One-way ANOVA
%
% Organization of the function:
% 1. Compute signals/spectra/features
% 2. Extract computed features into a table
% 3. Rank features
%
% Modify the function to add or remove data processing, feature generation
% or ranking operations.

% Auto-generated by MATLAB on 08-Jan-2026 13:26:16

FEATURES = ["fun1_Altitude";"fun2_Altitude";"fun3_Altitude";"fun4_Altitude";
    "fun1_Mach";"fun2_Mach";"fun3_Mach";"fun4_Mach";"fun1_Pamb";"fun2_Pamb";
    "fun3_Pamb";"fun4_Pamb";"fun1_Pt2";"fun2_Pt2";"fun3_Pt2";"fun4_Pt2";"fun1_TAT";
    "fun2_TAT";"fun3_TAT";"fun4_TAT";"fun1_WFuel";"fun2_WFuel";"fun3_WFuel";
    "fun4_WFuel";"fun1_VAFN";"fun2_VAFN";"fun3_VAFN";"fun4_VAFN";"fun1_VBV";
    "fun2_VBV";"fun3_VBV";"fun4_VBV";"fun1_Fan_Speed";"fun2_Fan_Speed";
    "fun3_Fan_Speed";"fun4_Fan_Speed";"fun1_Core_Speed";"fun2_Core_Speed";
    "fun3_Core_Speed";"fun4_Core_Speed";"fun1_T25";"fun2_T25";"fun3_T25";
    "fun4_T25";"fun1_T3";"fun2_T3";"fun3_T3";"fun4_T3";"fun1_Ps3";"fun2_Ps3";
    "fun3_Ps3";"fun4_Ps3";"fun1_T45";"fun2_T45";"fun3_T45";"fun4_T45";"fun1_P25";
    "fun2_P25";"fun3_P25";"fun4_P25";"fun1_T5";"fun2_T5";"fun3_T5";"fun4_T5"];
INDEPENDENT_VARIABLES = EVENT + "_index";
CONDITION_VARIABLES = "fault_" + EVENT;

% Create output ensemble.
outputEnsemble = workspaceEnsemble(inputData,'DataVariables',FEATURES, ...
    'IndependentVariables',INDEPENDENT_VARIABLES, ...
    'ConditionVariables',CONDITION_VARIABLES);


% Gather all features into a table.
selectedFeatureNames = FEATURES;
featureTable = readFeatureTable(outputEnsemble,'Features',selectedFeatureNames);

% Feature ranking for FeatureTable1

% Get selected features and labels for classification ranking.
selectedFeatureValues = featureTable{:,selectedFeatureNames};
label = featureTable{:,CONDITION_VARIABLES};

% Convert label to numeric values.
if iscategorical(label)
    label = string(label);
end
group = grp2idx(label);

% Initialize an empty matrix to store ranking scores.
score = zeros(numel(selectedFeatureNames),0);

% Initialize a string array to store ranking method names.
methodList = strings(0);

%% One-way ANOVA
% Normalize features using minmax.
fNorm = (selectedFeatureValues-min(selectedFeatureValues,[],1))./(max(selectedFeatureValues,[],1)-min(selectedFeatureValues,[],1));

% Compute ranking score using One-Way ANOVA.
numFeatures = size(fNorm,2);
z = zeros(numFeatures,1);
for k = 1:numFeatures
    [~,tbl] = anova1(fNorm(:,k),group,'off');
    % Get the F-statistic from the output of one-way ANOVA.
    stats = tbl{2,5};
    if ~isempty(stats)
        z(k) = stats;
    end
end

% Append new score and method name.
score = [score,z];
methodList = [methodList,"One-way ANOVA"];


%% Create ranking result table.
featureColumn = table(selectedFeatureNames(:),'VariableNames',{'Features'});
ranking = [featureColumn array2table(score,'VariableNames',methodList)];
ranking = sortrows(ranking,'One-way ANOVA','descend');

% Set SelectedVariables to select variables to read from the ensemble.
outputEnsemble.SelectedVariables = unique([outputEnsemble.DataVariables;outputEnsemble.ConditionVariables;outputEnsemble.IndependentVariables],'stable');

% Gather results into a table.
outputTable = readall(outputEnsemble);
end
