PLOT_PATH = f"./img/"
STAT_FEATURES_PATH = f"./img/STAT_FEATURES"
DATA_PATH = f"../../Data/PHM2025_training_data/training_data.csv"
DATA_BASE_PATH = f"../../Data/"
DATA_SIMULATION_PATH = f"../../Data/Simulation/"
DATA_TRAINING_PATH = f"../../Data/PHM2025_training_data/"
DATA_PATH_FFILL = f"../../Data/PHM2025_training_data/training_ffill.csv"
