% Fill missing data
T = fillmissing(T,"previous");

% Remove outliers
T = rmoutliers(T,"movmedian",2,ThresholdFactor=0.25, ...
    DataVariables=["Sensed_Altitude","Sensed_Mach","Sensed_Pamb","Sensed_Pt2", ...
    "Sensed_TAT","Sensed_WFuel","Sensed_VAFN","Sensed_VBV","Sensed_Fan_Speed", ...
    "Sensed_Core_Speed","Sensed_T25","Sensed_T3","Sensed_Ps3","Sensed_T45", ...
    "Sensed_P25","Sensed_T5"]);